### ISSUE TITLE
Executable missing

### ISSUE THREAD

**Issue by ThreeDeeJay** [Chatney/vr_media_viewer#1]
[VR_Media_viewer.7z](https://github.com/Chatney/vr_media_viewer/releases/download/what/VR_Media_viewer.7z) doesn't include VR Media viewer.exe 🤔 
![image](https://github.com/user-attachments/assets/c884c272-1b67-40d3-80c0-40e638fcf133)

**Comment by Chatney** [comment]
🤔 how about now

**Comment by ThreeDeeJay** [comment]
Thanks mate! 👍
